- CONTRIBUTING.md
- `server` is gone, suggest `meteroid-api` instead
> fix(readme): Suggest to run the meteroid-api

- .github/workflows/release-drafter.yml
It currently fails due https://github.com/release-drafter/release-drafter/issues/1125
Trying the suggested solution https://github.com/release-drafter/release-drafter/issues/1125#issuecomment-1471142225
> fix: Attempt to fix release-drafter

- .github/dependabot.yml
- Cargo.toml
- modules/web/package.json
cf https://github.com/meteroid-oss/meteroid/network/updates
> fix: dependabot is failing for cargo & npm

- .github/dependabot.yml
let's update all npm packages at once
> chore: use dependabot groups

- .github/workflows/docker.yaml
In case of timeout in the docker action caching, continue
> chore: ignore docker caching error

- .github/release-drafter.yml
- .github/workflows/docker.yaml
+ add a separate category for dependency updates
> fix: Publish docker latest tag only on release

- .github/dependabot.yml
- Cargo.toml
cf https://github.com/davidB/tracing-opentelemetry-instrumentation-sdk/issues/122
> chore: reverse and ignore tonic-tracing-opentelemetry

- Cargo.toml
- crates/common-repository/Cargo.toml
- crates/common-repository/src/lib.rs
- crates/cornucopia-build/Cargo.toml
- modules/meteroid/crates/meteroid-repository/Cargo.toml
- modules/meteroid/crates/meteroid-repository/src/lib.rs
update rustls (many changes) and other db-related libs
> chore: update tsl & db related deps

- .github/dependabot.yml
We need to wait for tonic : https://github.com/hyperium/tonic/issues/1579 (will take some time)
> chore: ignore http updates

- docker/demo/docker-compose.yml
> feat: web healthcheck

- .github/dependabot.yml
> chore(deps): Update dependabot.yml

- modules/meteroid/src/eventbus/memory.rs
Currently when the api server is terminated the Eventbus handler loop still continues to poll events resulting in a lot of errors in the logs. This PR addresses this issue.
> fix: Exit from eventbus loop when there are no active senders

- modules/meteroid/src/api/services/subscriptions/service.rs
- modules/meteroid/src/eventbus/mod.rs
- modules/meteroid/src/workers/invoicing/draft_worker.rs
- modules/meteroid/src/workers/invoicing/finalize_worker.rs
- modules/meteroid/tests/integration/e2e.rs
- modules/meteroid/tests/integration/meteroid_it/eventbus.rs
- modules/meteroid/tests/integration/meteroid_it/mod.rs
- modules/meteroid/tests/integration/test_workers.rs
> feat: send invoice.draft and invoice.finalized webhook events

- modules/meteroid/src/api/server.rs
- modules/meteroid/src/api/services/apitokens/mod.rs
- modules/meteroid/src/api/services/apitokens/service.rs
- modules/meteroid/src/eventbus/analytics_handler.rs
- modules/meteroid/src/eventbus/mod.rs
Added analytics (via segment) for api token RPC
> feat(analytics): api token related

- modules/meteroid/src/api/server.rs
- modules/meteroid/src/api/services/billablemetrics/mod.rs
- modules/meteroid/src/api/services/billablemetrics/service.rs
- modules/meteroid/src/eventbus/analytics_handler.rs
- modules/meteroid/src/eventbus/mod.rs
Added analytics for billable metrics
> feat(analytics): billable metric related

- modules/meteroid/src/api/services/customers/mod.rs
- modules/meteroid/src/api/services/customers/service.rs
- modules/meteroid/src/eventbus/analytics_handler.rs
- modules/meteroid/src/eventbus/mod.rs
Added analytics for patching of customer
> feat(analytics): customer patched

- modules/meteroid/src/api/server.rs
- modules/meteroid/src/api/services/instance/mod.rs
- modules/meteroid/src/api/services/instance/service.rs
- modules/meteroid/src/api/services/plans/mod.rs
- modules/meteroid/src/api/services/plans/service.rs
- modules/meteroid/src/api/services/pricecomponents/mod.rs
- modules/meteroid/src/api/services/pricecomponents/service.rs
- modules/meteroid/src/api/services/productfamilies/mod.rs
- modules/meteroid/src/api/services/productfamilies/service.rs
- modules/meteroid/src/api/services/users/mod.rs
- modules/meteroid/src/api/services/users/service.rs
- modules/meteroid/src/eventbus/analytics_handler.rs
- modules/meteroid/src/eventbus/mod.rs
Added
- instance
- plan
- price-component
- product-family
- user
> feat(analytics): extra events

- modules/meteroid/crates/meteroid-repository/queries/invoices.sql
- modules/meteroid/crates/meteroid-repository/src/cornucopia.rs
- modules/meteroid/proto/api/invoices/v1/invoices.proto
- modules/meteroid/src/api/services/invoices/service.rs
- modules/meteroid/tests/integration/e2e.rs
- modules/meteroid/tests/integration/test_workers.rs
- modules/web/web-app/components/layouts/shared/PageSection.tsx
- modules/web/web-app/components/molecules/Property.tsx
- modules/web/web-app/features/billing/plans/PlanBuilder.tsx
- modules/web/web-app/features/billing/plans/pricecomponents/PriceComponentSection.tsx
- modules/web/web-app/features/customers/cards/CardAction.tsx
- modules/web/web-app/features/customers/cards/InvoicesCard.tsx
- modules/web/web-app/features/customers/cards/address/AddressCard.tsx
- modules/web/web-app/features/customers/cards/balance/BalanceCard.tsx
- modules/web/web-app/features/customers/cards/balance/InvoicesCard.tsx
- modules/web/web-app/features/customers/cards/customer/CustomerCard.tsx
- modules/web/web-app/features/invoices/InvoicesTable.tsx
- modules/web/web-app/pages/tenants/customer/customer.tsx
- modules/web/web-app/styles/main.scss
- small UI fixes (color and spacing)
- add customer filter to the query
- display as table in the customer view
- let see how to reorganize this customer page when the chart components will be ready :)
> feat(customer): List customer invoices

- .github/workflows/ci-rust.yaml
- modules/meteroid/crates/meteroid-repository/src/cornucopia.rs
- modules/meteroid/src/eventbus/mod.rs
> fix: Set correct EventData type for ProductFamilyCreated event

- modules/meteroid/src/api/services/customers/error.rs
- modules/meteroid/src/api/services/customers/service.rs
> refactor(customers): use thiserror

- modules/meteroid/src/api/server.rs
- modules/meteroid/src/bin/server.rs
- modules/meteroid/src/eventbus/analytics_handler.rs
- modules/meteroid/src/eventbus/mod.rs
> feat(analytics): added country information in events

- modules/meteroid/src/api/subscriptions/service.rs
- modules/meteroid/src/eventbus/analytics_handler.rs
- modules/meteroid/src/eventbus/mod.rs
> chore: Send analytics event on subscription cancellation

- Cargo.toml
> chore: Update rust version to latest stable 1.77 version

- .github/workflows/docker.yaml
> fix: set release profile

- modules/meteroid/crates/meteroid-store/src/errors.rs
- modules/meteroid/crates/meteroid-store/src/lib.rs
- modules/meteroid/crates/meteroid-store/src/repositories/customers.rs
- modules/meteroid/crates/meteroid-store/src/repositories/invoices.rs
- modules/meteroid/crates/meteroid-store/src/repositories/mod.rs
- modules/meteroid/crates/meteroid-store/src/repositories/plans.rs
- modules/meteroid/crates/meteroid-store/src/repositories/product_families.rs
- modules/meteroid/crates/meteroid-store/src/repositories/subscriptions.rs
- modules/meteroid/crates/meteroid-store/src/repositories/tenants.rs
- modules/meteroid/crates/meteroid-store/src/utils/mod.rs
- modules/meteroid/crates/meteroid-store/src/utils/periods.rs
> chore: implement repositories layer

- Cargo.toml
- modules/meteroid/Cargo.toml
> chore(deps): bump reqwest libs

- Cargo.toml
> chore(deps): bump opentelemetry libs

- modules/meteroid/crates/diesel-models/src/extend/mod.rs
- modules/meteroid/crates/diesel-models/src/extend/order.rs
- modules/meteroid/crates/diesel-models/src/query/mod.rs
- modules/meteroid/crates/diesel-models/src/query/webhooks.rs
- modules/meteroid/crates/diesel-models/src/schema.rs
- modules/meteroid/crates/diesel-models/src/webhooks.rs
- modules/meteroid/crates/meteroid-store/Cargo.toml
- modules/meteroid/crates/meteroid-store/src/domain/configs.rs
- modules/meteroid/crates/meteroid-store/src/domain/misc.rs
- modules/meteroid/crates/meteroid-store/src/domain/mod.rs
- modules/meteroid/crates/meteroid-store/src/domain/webhooks.rs
- modules/meteroid/crates/meteroid-store/src/repositories/configs.rs
- modules/meteroid/crates/meteroid-store/src/repositories/mod.rs
- modules/meteroid/crates/meteroid-store/src/repositories/webhooks.rs
- modules/meteroid/crates/meteroid-store/src/utils/gen.rs
- modules/meteroid/crates/meteroid-store/src/utils/mod.rs
- modules/meteroid/src/api/server.rs
- modules/meteroid/src/api/utils.rs
- modules/meteroid/src/api/webhooksout/error.rs
- modules/meteroid/src/api/webhooksout/mapping.rs
- modules/meteroid/src/api/webhooksout/mod.rs
- modules/meteroid/src/api/webhooksout/service.rs
- modules/meteroid/tests/integration/test_webhooks_out.rs
> chore: migrate webhook_out to diesel

- modules/web/web-app/index.html
This meta tag is useful for screen readers to give the user information about the page, and so it's a potential a11y issue. This commit adds one.
> add meta description tag

- modules/meteroid/src/adapters/stripe.rs
- modules/meteroid/src/compute/clients/usage.rs
- modules/meteroid/src/mapping/common.rs
> chore: use non-deprecated timestamp functions

- modules/meteroid/proto/api/invoices/v1/invoices.proto
- modules/meteroid/proto/api/plans/v1/plans.proto
- modules/meteroid/proto/api/webhooksout/v1/webhooksout.proto
- modules/meteroid/src/api/invoices/service.rs
- modules/meteroid/src/api/plans/service.rs
- modules/meteroid/src/api/webhooksout/service.rs
- modules/meteroid/tests/integration/test_webhooks_out.rs
- modules/web/web-app/features/billing/plans/PlansTable.tsx
- modules/web/web-app/features/customers/cards/InvoicesCard.tsx
- modules/web/web-app/features/dashboard/sections/MrrSection.tsx
- modules/web/web-app/pages/tenants/invoice/Invoices.tsx
> refactor: naming convention - use sort_by instead of order_by

- modules/meteroid/src/api/customers/mapping.rs
- modules/meteroid/src/api/customers/service.rs
> Customers diesel: use TryFrom in mappings

- modules/meteroid/crates/diesel-models/src/customers.rs
- modules/meteroid/crates/diesel-models/src/extend/order.rs
- modules/meteroid/crates/diesel-models/src/query/customers.rs
- modules/meteroid/crates/diesel-models/src/query/webhooks.rs
- modules/meteroid/crates/meteroid-store/src/domain/customers.rs
- modules/meteroid/crates/meteroid-store/src/domain/misc.rs
- modules/meteroid/crates/meteroid-store/src/repositories/customers.rs
- modules/meteroid/src/api/customers/error.rs
- modules/meteroid/src/api/customers/mapping.rs
- modules/meteroid/src/api/customers/mod.rs
- modules/meteroid/src/api/customers/service.rs
- modules/meteroid/src/api/server.rs
- modules/meteroid/src/workers/invoicing/issue_worker.rs
- modules/meteroid/tests/integration/main.rs
- modules/meteroid/tests/integration/test_customer.rs
> chore: migrate customer to diesel 

- modules/meteroid/crates/diesel-models/src/plan_versions.rs
- modules/meteroid/crates/diesel-models/src/query/plan_versions.rs
- modules/meteroid/crates/diesel-models/src/query/schedules.rs
- modules/meteroid/crates/diesel-models/src/schedules.rs
- modules/meteroid/crates/diesel-models/src/schema.rs
- modules/meteroid/crates/meteroid-store/src/domain/adjustments/discount.rs
- modules/meteroid/crates/meteroid-store/src/domain/adjustments/mod.rs
- modules/meteroid/crates/meteroid-store/src/domain/mod.rs
- modules/meteroid/crates/meteroid-store/src/domain/plans.rs
- modules/meteroid/crates/meteroid-store/src/domain/schedules.rs
- modules/meteroid/crates/meteroid-store/src/repositories/mod.rs
- modules/meteroid/crates/meteroid-store/src/repositories/schedules.rs
- modules/meteroid/crates/meteroid-store/src/repositories/subscriptions.rs
- modules/meteroid/src/api/domain_mapping.rs
- modules/meteroid/src/api/schedules/error.rs
- modules/meteroid/src/api/schedules/mapping.rs
- modules/meteroid/src/api/schedules/mod.rs
- modules/meteroid/src/api/schedules/service.rs
- modules/meteroid/src/api/server.rs
- modules/meteroid/tests/data/2_plans.sql
- modules/meteroid/tests/integration/main.rs
- modules/meteroid/tests/integration/test_schedule.rs
Migrate schedules to diesel + add basic tests
> chore: migrate schedules to diesel

- modules/meteroid/crates/meteroid-store/src/errors.rs
- modules/meteroid/crates/meteroid-store/src/repositories/users.rs
- modules/meteroid/src/api/users/error.rs
- modules/meteroid/tests/integration/e2e.rs
- modules/meteroid/tests/integration/test_basic.rs
- modules/meteroid/tests/integration/test_customer.rs
- modules/meteroid/tests/integration/test_slot_transaction.rs
- modules/meteroid/tests/integration/test_subscription.rs
- modules/meteroid/tests/integration/test_webhooks_out.rs
- modules/meteroid/tests/integration/test_workers.rs
> chore: temporarily ignore failing tests

- modules/meteroid/proto/api/customers/v1/customers.proto
- modules/meteroid/src/api/customers/service.rs
- modules/web/web-app/features/customers/CustomerSelect.tsx
- modules/web/web-app/features/customers/cards/address/EditAddressModal.tsx
- modules/web/web-app/features/customers/cards/balance/EditBalanceModal.tsx
- modules/web/web-app/features/customers/cards/customer/EditCustomerModal.tsx
- modules/web/web-app/pages/tenants/customer/customer.tsx
Reverts meteroid-oss/meteroid#210
> Revert "refactor:  customer API - following naming convention"

- modules/meteroid/crates/diesel-models/src/billable_metrics.rs
- modules/meteroid/crates/diesel-models/src/enums.rs
- modules/meteroid/crates/diesel-models/src/query/billable_metrics.rs
- modules/meteroid/crates/meteroid-store/src/domain/billable_metrics.rs
- modules/meteroid/crates/meteroid-store/src/repositories/billable_metrics.rs
- modules/meteroid/crates/meteroid-store/src/repositories/mod.rs
- modules/meteroid/src/api/billablemetrics/error.rs
- modules/meteroid/src/api/billablemetrics/mapping.rs
- modules/meteroid/src/api/billablemetrics/mod.rs
- modules/meteroid/src/api/billablemetrics/service.rs
- modules/meteroid/src/api/server.rs
- modules/meteroid/src/eventbus/analytics_handler.rs
- modules/meteroid/tests/integration/main.rs
- modules/meteroid/tests/integration/test_billable_metric.rs
> chore: migrate billable metric to diesel

- modules/meteroid/crates/meteroid-store/Cargo.toml
- modules/meteroid/crates/meteroid-store/src/repositories/customers.rs
> fix: sending event on customer(s) creation

- modules/meteroid/src/eventbus/memory.rs
> feat: log on error on publishing event

- modules/meteroid/crates/meteroid-store/src/domain/subscriptions.rs
- modules/meteroid/crates/meteroid-store/src/repositories/subscriptions.rs
- modules/meteroid/src/api/server.rs
- modules/meteroid/src/api/subscriptions/mod.rs
> feat: subscription - added eventbus

- modules/meteroid/src/api/apitokens/error.rs
- modules/meteroid/src/api/billablemetrics/error.rs
- modules/meteroid/src/api/customers/error.rs
- modules/meteroid/src/api/pricecomponents/error.rs
- modules/meteroid/src/api/productfamilies/error.rs
- modules/meteroid/src/api/productitems/error.rs
- modules/meteroid/src/api/schedules/error.rs
- modules/meteroid/src/api/subscriptions/error.rs
- modules/meteroid/src/api/tenants/error.rs
- modules/meteroid/src/api/users/error.rs
- modules/meteroid/src/api/webhooksout/error.rs
> refactor: api errors

- modules/meteroid/crates/diesel-models/src/invoices.rs
- modules/meteroid/crates/diesel-models/src/query/invoices.rs
- modules/meteroid/crates/diesel-models/src/schema.rs
- modules/meteroid/crates/meteroid-store/src/domain/invoices.rs
- modules/meteroid/crates/meteroid-store/src/repositories/invoices.rs
- modules/meteroid/src/api/invoices/error.rs
- modules/meteroid/src/api/invoices/mapping.rs
- modules/meteroid/src/api/invoices/mod.rs
- modules/meteroid/src/api/invoices/service.rs
- modules/meteroid/src/api/server.rs
- modules/meteroid/src/api/tenants/error.rs
> chore: migrate invoice to diesel

- modules/meteroid/crates/diesel-models/src/query/price_components.rs
- modules/meteroid/crates/diesel-models/src/webhooks.rs
- modules/meteroid/crates/meteroid-repository/src/cornucopia.rs
- modules/meteroid/crates/meteroid-store/src/domain/enums.rs
- modules/meteroid/crates/meteroid-store/src/domain/webhooks.rs
- modules/meteroid/crates/meteroid-store/src/repositories/price_components.rs
- modules/meteroid/crates/meteroid-store/src/repositories/webhooks.rs
- modules/meteroid/src/api/server.rs
- modules/meteroid/src/bin/server.rs
- modules/meteroid/src/eventbus/analytics_handler.rs
- modules/meteroid/src/eventbus/mod.rs
- modules/meteroid/src/eventbus/webhook_handler.rs
- modules/meteroid/src/singletons.rs
- modules/meteroid/tests/integration/meteroid_it/container.rs
- modules/meteroid/tests/integration/test_webhooks_out.rs
> chore: migrate eventbus to diesel

- modules/meteroid/crates/diesel-models/src/subscriptions.rs
- modules/meteroid/crates/meteroid-store/src/repositories/organizations.rs
- modules/meteroid/src/api/instance/mod.rs
- modules/meteroid/src/api/server.rs
- modules/meteroid/src/bin/server.rs
- modules/meteroid/src/eventbus/mod.rs
- modules/meteroid/src/eventbus/webhook_handler.rs
- modules/meteroid/tests/integration/meteroid_it/container.rs
> chore: cleanup and remove unused imports

- modules/meteroid/Cargo.toml
- modules/meteroid/crates/diesel-models/src/bi.rs
- modules/meteroid/crates/diesel-models/src/historical_rates_from_usd.rs
- modules/meteroid/crates/diesel-models/src/lib.rs
- modules/meteroid/crates/diesel-models/src/query/historical_rates_from_usd.rs
- modules/meteroid/crates/diesel-models/src/query/mod.rs
- modules/meteroid/crates/meteroid-store/src/domain/historical_rates.rs
- modules/meteroid/crates/meteroid-store/src/domain/mod.rs
- modules/meteroid/crates/meteroid-store/src/repositories/historical_rates.rs
- modules/meteroid/crates/meteroid-store/src/repositories/mod.rs
- modules/meteroid/src/workers/misc/currency_rates_worker.rs
> chore: migrate historical rates to diesel

- crates/common-utils/src/lib.rs
- crates/common-utils/src/uuid.rs
- modules/meteroid/crates/diesel-models/src/query/invoices.rs
- modules/meteroid/crates/diesel-models/src/query/subscriptions.rs
- modules/meteroid/crates/diesel-models/src/query/webhooks.rs
- modules/meteroid/crates/diesel-models/src/webhooks.rs
- modules/meteroid/crates/meteroid-store/src/domain/enums.rs
- modules/meteroid/crates/meteroid-store/src/domain/webhooks.rs
- modules/meteroid/crates/meteroid-store/src/repositories/api_tokens.rs
- modules/meteroid/crates/meteroid-store/src/repositories/invoices.rs
- modules/meteroid/crates/meteroid-store/src/repositories/webhooks.rs
- modules/meteroid/src/adapters/stripe.rs
- modules/meteroid/src/adapters/types.rs
- modules/meteroid/src/bin/server.rs
- modules/meteroid/src/datetime.rs
- modules/meteroid/src/webhook_in_api.rs
- modules/meteroid/tests/integration/e2e.rs
> chore: migrate to diesel webhook-in api

- modules/meteroid/crates/meteroid-store/src/domain/customers.rs
- modules/meteroid/crates/meteroid-store/src/domain/enums.rs
- modules/meteroid/crates/meteroid-store/src/domain/invoices.rs
- modules/meteroid/src/workers/invoicing/draft_worker.rs
- modules/meteroid/tests/data/1_customers.sql
- modules/meteroid/tests/integration/e2e.rs
- modules/meteroid/tests/integration/test_workers.rs
- remove unused pool dep
- migrated to chrono
- migrated to store in tests
> chore: cleanup draft-worker

- modules/meteroid/crates/diesel-models/Cargo.toml
- modules/meteroid/crates/diesel-models/src/query/invoices.rs
- modules/meteroid/crates/meteroid-store/src/repositories/invoices.rs
- modules/meteroid/src/api/billablemetrics/mapping.rs
- modules/meteroid/src/workers/invoicing/finalize_worker.rs
- modules/meteroid/src/workers/invoicing/shared/line_items.rs
- modules/meteroid/src/workers/invoicing/shared/mod.rs
- modules/meteroid/tests/integration/e2e.rs
> chore: migrate to diesel finalize-worker

- modules/meteroid/crates/diesel-models/src/query/invoices.rs
- modules/meteroid/crates/meteroid-store/src/repositories/invoices.rs
- modules/meteroid/src/workers/invoicing/price_worker.rs
- modules/meteroid/src/workers/invoicing/shared/line_items.rs
- modules/meteroid/src/workers/invoicing/shared/mod.rs
- modules/meteroid/tests/integration/e2e.rs
> chore: migrate price_worker to diesel

- modules/meteroid/src/bin/seeder.rs
- fetch organization from DB instead of hardcoded
- create currency rates before seeder runs to fix historical_rate_id null issue
- use a timestamp for tenant name instead of random, so it's easier to differ them by the seeder run time.
> fix: Fix seeder so it works on clean env

- modules/meteroid/crates/diesel-models/src/enums.rs
- modules/meteroid/crates/diesel-models/src/query/customers.rs
- modules/meteroid/crates/diesel-models/src/query/invoices.rs
- modules/meteroid/crates/meteroid-migrations/refinery/migrations/V0036__invoicing_manual_provider.sql
- modules/meteroid/crates/meteroid-store/src/domain/enums.rs
- modules/meteroid/crates/meteroid-store/src/repositories/customers.rs
- modules/meteroid/proto/api/invoices/v1/models.proto
- modules/meteroid/src/adapters/stripe.rs
- modules/meteroid/src/api/invoices/mapping.rs
- modules/meteroid/src/webhook_in_api.rs
- modules/meteroid/src/workers/invoicing/draft_worker.rs
- modules/meteroid/src/workers/invoicing/issue_worker.rs
- modules/meteroid/tests/integration/metering_it/container.rs
- modules/meteroid/tests/integration/meteroid_it/container.rs
> feat: Add invoicing manual provider

- Cargo.toml
- crates/common-repository/Cargo.toml
- modules/meteroid/crates/diesel-models/src/query/price_components.rs
- modules/meteroid/crates/diesel-models/src/query/schedules.rs
- modules/meteroid/src/webhook_in_api.rs
- modules/meteroid/tests/integration/e2e.rs
- modules/meteroid/tests/integration/metering_it/container.rs
- modules/meteroid/tests/integration/meteroid_it/container.rs
- modules/meteroid/tests/integration/test_auth_api_key.rs
- modules/meteroid/tests/integration/test_auth_jwt.rs
- modules/meteroid/tests/integration/test_basic.rs
- modules/meteroid/tests/integration/test_billable_metric.rs
- modules/meteroid/tests/integration/test_customer.rs
- modules/meteroid/tests/integration/test_idempotency.rs
- modules/meteroid/tests/integration/test_idempotency_cache.rs
- modules/meteroid/tests/integration/test_instance.rs
- modules/meteroid/tests/integration/test_internal.rs
- modules/meteroid/tests/integration/test_plan.rs
- modules/meteroid/tests/integration/test_product.rs
- modules/meteroid/tests/integration/test_product_family.rs
- modules/meteroid/tests/integration/test_schedule.rs
- modules/meteroid/tests/integration/test_slot_transaction.rs
- modules/meteroid/tests/integration/test_stats.rs
- modules/meteroid/tests/integration/test_subscription.rs
- modules/meteroid/tests/integration/test_tenant.rs
- modules/meteroid/tests/integration/test_user.rs
- modules/meteroid/tests/integration/test_webhooks_out.rs
- modules/meteroid/tests/integration/test_workers.rs
> chore(deps): Bump some deps

- modules/meteroid/crates/diesel-models/src/query/customer_balance_txs.rs
- modules/meteroid/crates/meteroid-store/src/repositories/customer_balance.rs
- modules/meteroid/crates/meteroid-store/src/repositories/customers.rs
- modules/meteroid/crates/meteroid-store/src/repositories/invoices.rs
Convert pending tx to tx when invoice is paid.
> feat: Process pending tx on paid invoice

- modules/metering/src/auth.rs
- modules/meteroid/crates/meteroid-middleware/src/server/auth/strategies/jwt_strategy.rs
- modules/meteroid/src/eventbus/webhook_handler.rs
> chore: Use uuid instead of String as a cache keys

- modules/meteroid/crates/diesel-models/src/bi.rs
- modules/meteroid/crates/diesel-models/src/schema.rs
- modules/meteroid/crates/meteroid-migrations/refinery/migrations/V0041__tx_indices.sql
> fix: Fix latest migration

- modules/meteroid/crates/diesel-models/src/add_ons.rs
- modules/meteroid/crates/diesel-models/src/lib.rs
- modules/meteroid/crates/diesel-models/src/query/add_ons.rs
- modules/meteroid/crates/diesel-models/src/query/mod.rs
- modules/meteroid/crates/diesel-models/src/schema.rs
- modules/meteroid/crates/meteroid-grpc/build.rs
- modules/meteroid/crates/meteroid-grpc/src/lib.rs
- modules/meteroid/crates/meteroid-migrations/refinery/migrations/V0042__add_on.sql
- modules/meteroid/crates/meteroid-store/src/domain/add_ons.rs
- modules/meteroid/crates/meteroid-store/src/domain/mod.rs
- modules/meteroid/crates/meteroid-store/src/repositories/add_ons.rs
- modules/meteroid/crates/meteroid-store/src/repositories/mod.rs
- modules/meteroid/proto/api/addons/v1/addons.proto
- modules/meteroid/proto/api/addons/v1/models.proto
- modules/meteroid/src/api/addons/error.rs
- modules/meteroid/src/api/addons/mapping.rs
- modules/meteroid/src/api/addons/mod.rs
- modules/meteroid/src/api/addons/service.rs
- modules/meteroid/src/api/mod.rs
- modules/meteroid/src/api/pricecomponents/mapping.rs
- modules/meteroid/src/api/server.rs
- modules/meteroid/tests/integration/main.rs
- modules/meteroid/tests/integration/meteroid_it/clients.rs
- modules/meteroid/tests/integration/test_add_ons.rs
> feat: Add add-ons api

- modules/meteroid/crates/diesel-models/src/coupons.rs
- modules/meteroid/crates/diesel-models/src/lib.rs
- modules/meteroid/crates/diesel-models/src/query/add_ons.rs
- modules/meteroid/crates/diesel-models/src/query/coupons.rs
- modules/meteroid/crates/diesel-models/src/query/mod.rs
- modules/meteroid/crates/diesel-models/src/schema.rs
- modules/meteroid/crates/meteroid-grpc/build.rs
- modules/meteroid/crates/meteroid-grpc/src/lib.rs
- modules/meteroid/crates/meteroid-store/src/domain/coupons.rs
- modules/meteroid/crates/meteroid-store/src/domain/mod.rs
- modules/meteroid/crates/meteroid-store/src/repositories/coupons.rs
- modules/meteroid/crates/meteroid-store/src/repositories/mod.rs
- modules/meteroid/migrations/diesel/2024-09-04-175914_coupons/down.sql
- modules/meteroid/migrations/diesel/2024-09-04-175914_coupons/up.sql
- modules/meteroid/proto/api/coupons/v1/coupons.proto
- modules/meteroid/proto/api/coupons/v1/models.proto
- modules/meteroid/src/api/coupons/error.rs
- modules/meteroid/src/api/coupons/mapping.rs
- modules/meteroid/src/api/coupons/mod.rs
- modules/meteroid/src/api/coupons/service.rs
- modules/meteroid/src/api/mod.rs
- modules/meteroid/src/api/server.rs
- modules/meteroid/src/api/shared.rs
- modules/meteroid/src/migrations.rs
- modules/meteroid/tests/integration/main.rs
- modules/meteroid/tests/integration/meteroid_it/clients.rs
- modules/meteroid/tests/integration/test_coupon.rs
> feat: Add coupons api

- .github/dependabot.yml
- Cargo.toml
- crates/common-grpc/src/middleware/server/auth/mod.rs
- modules/metering/crates/metering-grpc/build.rs
- modules/metering/src/server.rs
- modules/meteroid/Cargo.toml
- modules/meteroid/crates/meteroid-grpc/build.rs
- modules/meteroid/src/api/axum_routers/webhook_in_router.rs
- modules/meteroid/src/api/axum_server.rs
- modules/meteroid/src/api/billablemetrics/service.rs
- modules/meteroid/src/api/server.rs
> chore(deps): upgraded tonic / axum / prost / opentelemetry / http / http_body / etc

- .env.example
> chore: Update .env.example minio

- CONTRIBUTING.md
- modules/meteroid/crates/diesel-models/src/errors.rs
- modules/meteroid/crates/diesel-models/src/lib.rs
- modules/meteroid/crates/diesel-models/src/query/coupons.rs
- modules/meteroid/crates/diesel-models/src/query/mod.rs
- modules/meteroid/crates/diesel-models/src/query/subscription_coupons.rs
- modules/meteroid/crates/diesel-models/src/schema.rs
- modules/meteroid/crates/diesel-models/src/subscription_coupons.rs
- modules/meteroid/crates/meteroid-store/src/domain/coupons.rs
- modules/meteroid/crates/meteroid-store/src/domain/historical_rates.rs
- modules/meteroid/crates/meteroid-store/src/domain/mod.rs
- modules/meteroid/crates/meteroid-store/src/domain/subscription_coupons.rs
- modules/meteroid/crates/meteroid-store/src/domain/subscriptions.rs
- modules/meteroid/crates/meteroid-store/src/repositories/historical_rates.rs
- modules/meteroid/crates/meteroid-store/src/repositories/subscriptions.rs
- modules/meteroid/migrations/diesel/2024-09-29-142325_subscription_coupons/down.sql
- modules/meteroid/migrations/diesel/2024-09-29-142325_subscription_coupons/up.sql
- modules/meteroid/proto/api/subscriptions/v1/models.proto
- modules/meteroid/src/api/coupons/mapping.rs
- modules/meteroid/src/api/coupons/mod.rs
- modules/meteroid/src/api/subscriptions/mapping.rs
- modules/meteroid/src/bin/server.rs
- modules/meteroid/src/migrations.rs
- modules/meteroid/src/seeder/runner.rs
- modules/meteroid/tests/integration/e2e.rs
- modules/meteroid/tests/integration/meteroid_it/container.rs
Apply coupons to subscriptions.
TODO
> feat: Subscription coupons

- Cargo.toml
Should fix https://github.com/meteroid-oss/meteroid/actions/runs/11239310735/job/31246076049
> fix: Add log feature to tracing crate

- Cargo.toml
- crates/common-logging/src/init.rs
> fix: update init telemetry

- Cargo.toml
- crates/distributed-lock/src/locks/postgres_lock.rs
- docker/develop/docker-compose.yml
- modules/adapters/slurm-collector/src/main.rs
- modules/meteroid/crates/meteroid-grpc/Cargo.toml
- modules/meteroid/crates/meteroid-grpc/clippy.toml
- modules/meteroid/crates/meteroid-store/src/domain/misc.rs
- modules/meteroid/proto/api/webhooksout/v1/webhooksout.proto
- modules/meteroid/src/bin/server.rs
- modules/meteroid/src/config.rs
- modules/meteroid/tests/integration/meteroid_it/config.rs
> chore: Upgrade svix to 1.42.0

- crates/kafka/src/config.rs
- crates/kafka/src/consumer.rs
- modules/metering/src/ingest/sinks/kafka.rs
- modules/meteroid/Cargo.toml
- modules/meteroid/crates/meteroid-store/src/domain/outbox_event.rs
- modules/meteroid/crates/meteroid-store/src/domain/webhooks.rs
- modules/meteroid/crates/meteroid-store/src/errors.rs
- modules/meteroid/crates/meteroid-store/src/repositories/webhooks.rs
- modules/meteroid/crates/meteroid-store/src/store.rs
- modules/meteroid/src/bin/scheduler.rs
- modules/meteroid/src/bin/server.rs
- modules/meteroid/src/config.rs
- modules/meteroid/src/lib.rs
- modules/meteroid/src/singletons.rs
- modules/meteroid/src/svix.rs
- modules/meteroid/src/workers/kafka/mod.rs
- modules/meteroid/src/workers/kafka/outbox.rs
- modules/meteroid/src/workers/kafka/processor.rs
- modules/meteroid/src/workers/kafka/processors.rs
- modules/meteroid/src/workers/kafka/webhook.rs
- modules/meteroid/src/workers/mod.rs
- modules/meteroid/tests/integration/metering_it/config.rs
- modules/meteroid/tests/integration/meteroid_it/config.rs
Introduces kafka processor and webhook implementation that reads the outbox events from kafka and publishes webhooks to svix.
**Note**: This version is a raw one, I left a couple of todos in the code for improvements.
> feat: Webhook kafka processor

- Cargo.toml
- modules/meteroid/Cargo.toml
- modules/meteroid/src/api_rest/mod.rs
- modules/meteroid/src/api_rest/openapi.rs
- modules/meteroid/src/api_rest/server.rs
- modules/meteroid/src/api_rest/subscriptions/mapping.rs
- modules/meteroid/src/api_rest/subscriptions/mod.rs
- modules/meteroid/src/api_rest/subscriptions/model.rs
- modules/meteroid/src/api_rest/subscriptions/router.rs
- spec/api/v1/openapi.json
> feat: Open API for subscription details

- .github/workflows/ci-rust.yaml
- modules/meteroid/crates/diesel-models/src/query/mod.rs
- modules/meteroid/crates/diesel-models/src/query/subscriptions.rs
- modules/meteroid/crates/meteroid-store/src/domain/mod.rs
- modules/meteroid/crates/meteroid-store/src/repositories/invoices.rs
- modules/meteroid/crates/meteroid-store/src/repositories/subscriptions.rs
- modules/meteroid/src/api/subscriptions/service.rs
- modules/meteroid/src/api_rest/subscriptions/mapping.rs
- modules/meteroid/src/api_rest/subscriptions/model.rs
- modules/meteroid/src/api_rest/subscriptions/router.rs
- modules/meteroid/src/eventbus/analytics_handler.rs
- modules/meteroid/src/seeder/runner.rs
- spec/api/v1/openapi.json
> chore: Use local_id in subscription rest api

- .github/workflows/audit-rust.yaml
- Cargo.toml
- audit.toml
- crates/common-grpc/Cargo.toml
- crates/common-logging/Cargo.toml
- crates/common-utils/Cargo.toml
- crates/distributed-lock/Cargo.toml
- crates/kafka/Cargo.toml
- docker/develop/docker-compose.yml
- extra/generator/Cargo.toml
- modules/adapters/openstack/Cargo.toml
- modules/adapters/slurm-collector/Cargo.toml
- modules/metering/Cargo.toml
- modules/meteroid/Cargo.toml
- modules/meteroid/crates/diesel-models/Cargo.toml
- modules/meteroid/crates/meteroid-grpc/Cargo.toml
- modules/meteroid/crates/meteroid-invoicing/Cargo.toml
- modules/meteroid/crates/meteroid-middleware/Cargo.toml
- modules/meteroid/crates/meteroid-store/Cargo.toml
- modules/meteroid/crates/meteroid-store/src/domain/webhooks.rs
- modules/meteroid/crates/stripe-client/Cargo.toml
- modules/meteroid/src/api/utils.rs
> chore: Add rust audit GitHub action

- README.md
- modules/web/web-app/features/dashboard/Dashboard.tsx
> chore: Happy new 2025 year

- crates/kafka/src/config.rs
- modules/meteroid/crates/meteroid-invoicing/Cargo.toml
- modules/meteroid/crates/meteroid-invoicing/src/html_render.rs
> chore: Fix rust lint

- modules/meteroid/src/api/subscriptions/mapping.rs
> chore: Add validation for TieredAndVolume

- docker/develop/data/seed.sql
- modules/meteroid/crates/diesel-models/src/errors.rs
- modules/meteroid/crates/diesel-models/src/query/stats.rs
- modules/meteroid/crates/diesel-models/src/query/tenants.rs
- modules/meteroid/crates/diesel-models/src/schema.rs
- modules/meteroid/crates/diesel-models/src/tenants.rs
- modules/meteroid/crates/meteroid-grpc/src/lib.rs
- modules/meteroid/crates/meteroid-store/src/domain/tenants.rs
- modules/meteroid/crates/meteroid-store/src/repositories/plans.rs
- modules/meteroid/crates/meteroid-store/src/repositories/stats.rs
- modules/meteroid/crates/meteroid-store/src/repositories/tenants.rs
- modules/meteroid/migrations/diesel/2025-01-20-000001_bank_accounts/down.sql
- modules/meteroid/migrations/diesel/2025-01-20-000001_bank_accounts/up.sql
- modules/meteroid/proto/api/tenants/v1/models.proto
- modules/meteroid/proto/api/tenants/v1/tenants.proto
- modules/meteroid/src/api/tenants/mapping.rs
- modules/meteroid/src/api/tenants/service.rs
- modules/meteroid/tests/data/0_minimal.sql
- modules/meteroid/tests/integration/test_basic.rs
- modules/meteroid/tests/integration/test_tenant.rs
Allow users to define the currencies available for their tenant
> feat: Available currencies

- .github/workflows/docker.yaml
> chore(ARM): Github now supports arm runners

- Cargo.toml
- crates/common-logging/Cargo.toml
- crates/common-logging/src/init.rs
- docker/develop/docker-compose.yml
- docker/develop/volume/grafana/provisioning/datasources/loki.yaml
- docker/develop/volume/loki/local-config.yaml
- docker/develop/volume/otelcollector/otelcol-config.yml
- modules/meteroid/crates/meteroid-store/src/repositories/users.rs
OpenTelemetryTracingBridge -> otel-collector -> loki -> grafana
> feat: Export logs to loki

- modules/meteroid/migrations/diesel/2025-01-30-235223_fix_tenant_constraint/down.sql
- modules/meteroid/migrations/diesel/2025-01-30-235223_fix_tenant_constraint/up.sql
- modules/meteroid/tests/integration/meteroid_it/container.rs
- modules/web/web-app/lib/env.ts
> fix: tenant slug should be unique locally

- .github/workflows/docker.yaml
- modules/meteroid/src/api_rest/server.rs
> chore: health endpoint & improve docker tags

- .github/workflows/docker.yaml
a test, adapted from Arroyo
our images were not properly tagged (the arm one specifically) making gitops complex
> chore: attempt to clean docker meta

- Cargo.toml
- modules/meteroid/Cargo.toml
- modules/meteroid/src/api_rest/customers/model.rs
- modules/meteroid/src/api_rest/customers/router.rs
- modules/meteroid/src/api_rest/model.rs
- modules/meteroid/src/api_rest/plans/model.rs
- modules/meteroid/src/api_rest/plans/router.rs
- modules/meteroid/src/api_rest/subscriptions/model.rs
- modules/meteroid/src/api_rest/subscriptions/router.rs
introduce validator so we can add validation rules to our apis
> feat: Introduce validation for rest api

- Cargo.toml
- docker/develop/docker-compose.yml
- modules/meteroid/crates/meteroid-store/src/domain/add_ons.rs
- modules/meteroid/crates/meteroid-store/src/domain/billable_metrics.rs
- modules/meteroid/crates/meteroid-store/src/domain/coupons.rs
- modules/meteroid/crates/meteroid-store/src/domain/customers.rs
- modules/meteroid/crates/meteroid-store/src/domain/macros.rs
- modules/meteroid/crates/meteroid-store/src/domain/mod.rs
- modules/meteroid/crates/meteroid-store/src/domain/price_components.rs
- modules/meteroid/crates/meteroid-store/src/domain/schedules.rs
- modules/meteroid/crates/meteroid-store/src/domain/subscription_add_ons.rs
- modules/meteroid/crates/meteroid-store/src/domain/subscription_components.rs
- modules/meteroid/crates/meteroid-store/src/domain/webhooks.rs
- modules/meteroid/crates/meteroid-store/src/errors.rs
- modules/meteroid/crates/meteroid-store/src/repositories/customers.rs
- modules/meteroid/crates/meteroid-store/src/repositories/plans.rs
- modules/meteroid/crates/meteroid-store/src/repositories/webhooks.rs
- modules/meteroid/src/api/customers/service.rs
- modules/meteroid/src/svix.rs
Reduce the boilerplate when serealize/deserialize to/from json
> chore: Introduce a macro that generates json serde

- crates/common-eventbus/src/lib.rs
- modules/meteroid/crates/diesel-models/src/customers.rs
- modules/meteroid/crates/diesel-models/src/query/customers.rs
- modules/meteroid/crates/meteroid-store/src/domain/customers.rs
- modules/meteroid/crates/meteroid-store/src/repositories/customers.rs
- modules/meteroid/src/api_rest/customers/mapping.rs
- modules/meteroid/src/api_rest/customers/mod.rs
- modules/meteroid/src/api_rest/customers/model.rs
- modules/meteroid/src/api_rest/customers/router.rs
- modules/meteroid/src/eventbus/analytics_handler.rs
- spec/api/v1/openapi.json
> feat: Add customer update rest api

- Cargo.toml
- modules/meteroid/crates/diesel-models/src/customers.rs
- modules/meteroid/crates/diesel-models/src/query/customers.rs
- modules/meteroid/crates/diesel-models/src/query/subscriptions.rs
- modules/meteroid/crates/diesel-models/src/schema.rs
- modules/meteroid/crates/meteroid-store/src/domain/customers.rs
- modules/meteroid/crates/meteroid-store/src/domain/webhooks.rs
- modules/meteroid/crates/meteroid-store/src/repositories/customers.rs
- modules/meteroid/migrations/diesel/2025-02-20-090129_customer_archived_by/down.sql
- modules/meteroid/migrations/diesel/2025-02-20-090129_customer_archived_by/up.sql
- modules/meteroid/proto/api/customers/v1/customers.proto
- modules/meteroid/src/api/customers/service.rs
- modules/meteroid/src/api_rest/customers/mod.rs
- modules/meteroid/src/api_rest/customers/router.rs
- spec/api/v1/openapi.json
> feat: Add customer delete apis

- Cargo.toml
- crates/common-grpc/src/middleware/server/auth/admin_layer.rs
- modules/metering/src/auth.rs
- modules/meteroid/crates/meteroid-middleware/src/server/auth/api_layer.rs
- modules/meteroid/crates/meteroid-store/src/repositories/subscriptions.rs
- modules/meteroid/src/api/subscriptions/service.rs
- modules/meteroid/src/api_rest/auth.rs
> chore: Update rust to 1.85

- crates/common-domain/src/ids/mod.rs
- modules/meteroid/crates/diesel-models/src/bi.rs
- modules/meteroid/crates/diesel-models/src/credit_notes.rs
- modules/meteroid/crates/diesel-models/src/customer_balance_txs.rs
- modules/meteroid/crates/diesel-models/src/invoices.rs
- modules/meteroid/crates/diesel-models/src/query/customer_balance_txs.rs
- modules/meteroid/crates/diesel-models/src/query/invoices.rs
- modules/meteroid/crates/diesel-models/src/schema.rs
- modules/meteroid/crates/diesel-models/src/stats.rs
- modules/meteroid/crates/meteroid-store/src/domain/invoices.rs
- modules/meteroid/crates/meteroid-store/src/domain/outbox_event.rs
- modules/meteroid/crates/meteroid-store/src/repositories/customer_balance.rs
- modules/meteroid/crates/meteroid-store/src/repositories/invoices.rs
- modules/meteroid/crates/stripe-client/src/invoice.rs
- modules/meteroid/migrations/diesel/2025-02-24-195833_invoice_delete_local_id/down.sql
- modules/meteroid/migrations/diesel/2025-02-24-195833_invoice_delete_local_id/up.sql
- modules/meteroid/src/adapters/stripe.rs
- modules/meteroid/src/api/invoices/mapping.rs
- modules/meteroid/src/api/invoices/service.rs
- modules/meteroid/src/api_rest/files/router.rs
- modules/meteroid/src/eventbus/analytics_handler.rs
- modules/meteroid/src/services/invoice_rendering.rs
- modules/meteroid/src/workers/invoicing/draft_worker.rs
- modules/meteroid/src/workers/kafka/pdf_renderer.rs
- modules/meteroid/src/workers/kafka/webhook.rs
> chore: Remove invoice local_id

- CONTRIBUTING.md
- docker/develop/for-frontends/docker-compose-light.yml
> chore: docker compose for fe

- modules/meteroid/crates/meteroid-store/src/domain/oauth.rs
- modules/meteroid/crates/meteroid-store/src/repositories/connectors.rs
- modules/meteroid/src/api/connectors/service.rs
- modules/meteroid/src/api/utils.rs
- modules/meteroid/src/api_rest/oauth/router.rs
> fix: Fix hubspot redirect url in case of successful connection

- Cargo.toml
- modules/meteroid/crates/diesel-models/src/query/connectors.rs
- modules/meteroid/crates/meteroid-oauth/Cargo.toml
- modules/meteroid/crates/meteroid-oauth/src/model.rs
- modules/meteroid/crates/meteroid-oauth/src/service.rs
- modules/meteroid/crates/meteroid-store/src/errors.rs
- modules/meteroid/crates/meteroid-store/src/repositories/connectors.rs
- modules/meteroid/crates/meteroid-store/src/repositories/oauth.rs
- modules/meteroid/src/api/connectors/service.rs
- modules/meteroid/src/api_rest/oauth/router.rs
- make OauthService error agnostic (hubspot doesn't use standard error response body)
- introduce exchange_refresh_token
- get_user_info takes an access_token as input
- fix oauth_exchange_code
> chore: Polish Oauth service

- .github/workflows/ci-rust.yaml
- Cargo.toml
- modules/metering/Dockerfile
- modules/meteroid/api.Dockerfile
- modules/meteroid/crates/meteroid-store/src/crypt.rs
- modules/meteroid/scheduler.Dockerfile
> chore: Update rust to 1.86.0

- crates/common-grpc/src/middleware/client/auth/admin_layer.rs
- crates/common-grpc/src/middleware/client/metric/layer.rs
- crates/common-grpc/src/middleware/server/auth/admin_layer.rs
- crates/common-grpc/src/middleware/server/error_logger/layer.rs
- crates/common-grpc/src/middleware/server/metric/layer.rs
- modules/metering/src/auth.rs
- modules/meteroid/crates/meteroid-middleware/src/server/auth/api_layer.rs
- modules/meteroid/src/api_rest/auth.rs
> chore: Use tower BoxError instead of custom BoxError

- modules/meteroid/crates/hubspot-client/src/deals.rs
- modules/meteroid/crates/hubspot-client/src/properties.rs
- modules/meteroid/proto/api/connectors/v1/models.proto
- modules/meteroid/proto/api/customers/v1/models.proto
- modules/meteroid/proto/api/subscriptions/v1/models.proto
- modules/meteroid/src/api/connectors/mapping.rs
- modules/meteroid/src/api/customers/mapping.rs
- modules/meteroid/src/api/subscriptions/mapping.rs
- modules/meteroid/src/services/subscription/ext.rs
- modules/meteroid/src/workers/pgmq/hubspot_sync.rs
> chore: Sync subscription status to hubspot

- modules/meteroid/src/workers/pgmq/pennylane_sync.rs
> fix: Do not sync billing_iban for pennylane

- Cargo.toml
- crates/kafka/Cargo.toml
- crates/kafka/src/lib.rs
- crates/kafka/src/processor.rs
- modules/metering/Cargo.toml
- modules/metering/migrations/refinery/V2__preprocessed_events.rs
- modules/metering/src/auth.rs
- modules/metering/src/bin/server.rs
- modules/metering/src/config.rs
- modules/metering/src/ingest/domain.rs
- modules/metering/src/ingest/sinks/kafka.rs
- modules/metering/src/lib.rs
- modules/metering/src/preprocessor/handler.rs
- modules/metering/src/preprocessor/mod.rs
- modules/metering/src/server.rs
- modules/meteroid/crates/diesel-models/src/query/billable_metrics.rs
- modules/meteroid/crates/meteroid-store/src/repositories/billable_metrics.rs
- modules/meteroid/proto/internal/v1/internal.proto
- modules/meteroid/src/api/internal/service.rs
- modules/meteroid/src/bin/standalone.rs
- modules/meteroid/tests/integration/e2e.rs
- modules/meteroid/tests/integration/metering_it/config.rs
- modules/meteroid/tests/integration/metering_it/container.rs
- modules/meteroid/tests/integration/test_metering_ingestion.rs
Add raw events preprocessor that enriches events with billable metric info and publish them into a dedicated clickhouse table.
> feat: Raw events preprocessor

- modules/web/web-app/pages/tenants/subscription/create/StepPlanAndCustomer.tsx
> chore: remove component banner

- docker/develop/docker-compose.yml
- modules/meteroid/crates/pennylane-client/src/customer_invoices.rs
- modules/meteroid/src/workers/pgmq/pennylane_sync.rs
- modules/meteroid/tests/integration/metering_it/clickhouse.rs
> feat: Set imputation_dates for pennylane invoice lines

- modules/web/web-app/Dockerfile
> fix: upgrade pnpm & node

- modules/metering/src/connectors/clickhouse/mod.rs
- modules/metering/src/connectors/clickhouse/sql/query_meter.rs
- modules/meteroid/src/workers/pgmq/billable_metric_sync.rs
- modules/meteroid/src/workers/pgmq/processors.rs
- modules/meteroid/tests/integration/metering_it/clickhouse.rs
- modules/meteroid/tests/integration/test_metering_ingestion.rs
- fixed billable metric sync worker
- fixed the usage query
- added test
> fix: Fix billable metric metering view

- modules/metering/src/server.rs
- modules/meteroid/crates/meteroid-store/src/repositories/users.rs
- modules/meteroid/crates/meteroid-store/src/store.rs
- modules/meteroid/src/api/users/service.rs
- modules/meteroid/src/bin/seeder.rs
- modules/meteroid/src/config.rs
- modules/meteroid/src/singletons.rs
- modules/meteroid/tests/integration/meteroid_it/config.rs
- modules/meteroid/tests/integration/meteroid_it/container.rs
- modules/meteroid/tests/integration/test_slot_transaction.rs
- modules/web/web-app/features/auth/components/LoginForm.tsx
> chore: add domain whitelist

- modules/web/web-app/lib/schemas/me.ts
> chore: Password length validation

- modules/meteroid/src/api_rest/model.rs
- modules/meteroid/src/api_rest/plans/model.rs
- modules/meteroid/src/api_rest/subscriptions/mapping.rs
- modules/meteroid/src/api_rest/subscriptions/model.rs
- spec/api/v1/openapi.json
> chore: Use a single format for rest enums

- modules/meteroid/crates/meteroid-store/src/domain/oauth.rs
- modules/meteroid/src/api_rest/mod.rs
- modules/meteroid/src/api_rest/oauth/router.rs
- modules/web/web-app/features/auth/components/AuthFormLayout.tsx
- modules/web/web-app/pages/auth/login.tsx
- modules/web/web-app/pages/auth/oauth-success.tsx
- modules/web/web-app/router/anonymous.tsx
> feat: Add Google oauth login and registration

- Cargo.toml
- modules/meteroid/crates/meteroid-store/Cargo.toml
- modules/meteroid/crates/meteroid-store/src/lib.rs
> chore: Upgrade lapin to 3.x

- modules/meteroid/scheduler.Dockerfile
> chore: Upgrade rust version in scheduler

- modules/meteroid/src/bootstrap/mod.rs
> chore: log svix bootstrap errors

- modules/meteroid/crates/pennylane-client/src/customers.rs
- modules/meteroid/src/workers/pgmq/pennylane_sync.rs
either we included it by mistake or it was removed from their api
> chore: remove billing_email from pennylane

- modules/meteroid/crates/pennylane-client/api.http
- modules/meteroid/crates/pennylane-client/src/client.rs
- modules/meteroid/crates/pennylane-client/src/customer_invoices.rs
- modules/meteroid/crates/pennylane-client/src/customers.rs
- modules/meteroid/crates/pennylane-client/src/lib.rs
- modules/meteroid/crates/pennylane-client/src/model.rs
- modules/meteroid/src/workers/pgmq/pennylane_sync.rs
> chore: Upsert for pennylane sync

- modules/meteroid/crates/pennylane-client/Cargo.toml
- modules/meteroid/crates/pennylane-client/src/client.rs
- modules/meteroid/crates/pennylane-client/src/model.rs
> fix: Fix query params serialization for pennylane

- modules/web/web-app/pages/tenants/customer/customer.tsx
- modules/web/web-app/pages/tenants/invoice/Invoice.tsx
- modules/web/web-app/pages/tenants/subscription/subscription.tsx
- modules/web/web-app/pages/tenants/utils.ts
> chore: Take the latest connection metadata for the integration

- modules/meteroid/crates/meteroid-store/src/domain/outbox_event.rs
- modules/meteroid/crates/meteroid-store/src/repositories/customers.rs
- modules/meteroid/src/workers/pgmq/outbox.rs
- modules/meteroid/src/workers/webhook_out.rs
> chore: Sync with integrations customer updates

- modules/meteroid/crates/meteroid-store/src/domain/outbox_event.rs
- modules/meteroid/src/workers/pgmq/webhook_out.rs
> chore: Log errors in webhook_out pgmq processor

- modules/meteroid/crates/pennylane-client/src/customer_invoices.rs
- modules/meteroid/crates/pennylane-client/src/customers.rs
- modules/web/web-app/lib/schemas/invoices.ts
- modules/web/web-app/pages/tenants/invoice/invoiceCreate.tsx
> fix: Fix invoice line dates

- modules/meteroid/crates/meteroid-invoicing/examples/typst_invoices.rs
- modules/meteroid/crates/meteroid-invoicing/l10n/en-US/invoice.ftl
- modules/meteroid/crates/meteroid-invoicing/l10n/fr-FR/invoice.ftl
- modules/meteroid/crates/meteroid-invoicing/src/model.rs
- modules/meteroid/crates/meteroid-invoicing/src/typst_render.rs
- modules/meteroid/crates/meteroid-invoicing/templates/invoice.typ
- modules/meteroid/crates/meteroid-invoicing/templates/main.typ
- modules/meteroid/crates/meteroid-invoicing/tests/typst_validation.rs
- modules/meteroid/src/api/invoices/service.rs
- modules/meteroid/src/services/invoice_rendering.rs
> chore: Display invoice discount

- modules/meteroid/crates/meteroid-invoicing/src/model.rs
- modules/meteroid/crates/meteroid-invoicing/src/typst_render.rs
- modules/meteroid/src/services/invoice_rendering.rs
- modules/web/web-app/features/settings/tabs/CompanyTab.tsx
- modules/web/web-app/pages/tenants/customer/customer.tsx
- invoice preview errors when logo set
- invoicing entity form errors
- display invoicing entity on customer page
> chore: Multiple bug fixes

- modules/web/web-app/features/quotes/QuoteView.tsx
- modules/web/web-app/pages/tenants/quotes/CreateQuote.tsx
> fix: Display default price component in quote preview

- .github/workflows/ci-rust.yaml
- Cargo.toml
- modules/adapters/openstack/src/events.rs
- modules/metering/Dockerfile
- modules/meteroid/api.Dockerfile
- modules/meteroid/scheduler.Dockerfile
- modules/meteroid/src/api/plans/mapping.rs
> chore: Upgrade rust to 1.90

- modules/metering/migrations/refinery/V3__kafka_sasl_auth.rs
> fix: ch migration

- modules/metering/src/migrations.rs
> chore: add cluster aware ch migrations

- .github/workflows/ci-rust.yaml
- modules/metering/src/connectors/clickhouse/mod.rs
> chore: add logs to meter query

- modules/meteroid/proto/api/plans/v1/plans.proto
- modules/meteroid/src/api/plans/service.rs
- modules/meteroid/tests/integration/e2e.rs
- modules/meteroid/tests/integration/test_basic.rs
- modules/meteroid/tests/integration/test_plan.rs
- modules/web/web-app/features/plans/create/details/DetailsForm.tsx
- modules/web/web-app/lib/schemas/plans.ts
> fix: add plan currency to draft api

- modules/web/web-app/features/events/EventsPage.tsx
> fix: Align positioning of event code

- modules/meteroid/crates/diesel-models/src/query/billable_metrics.rs
- modules/meteroid/crates/meteroid-store/src/repositories/billable_metrics.rs
- modules/meteroid/proto/api/billablemetrics/v1/billablemetrics.proto
- modules/meteroid/src/api/billablemetrics/service.rs
- modules/web/web-app/features/productCatalog/metrics/AggregationSection.tsx
- modules/web/web-app/features/productCatalog/metrics/ProductMetricsEditPanel.tsx
- modules/web/web-app/features/productCatalog/metrics/ProductMetricsPageHeader.tsx
- modules/web/web-app/features/productCatalog/metrics/ProductMetricsTable.tsx
- modules/web/web-app/features/productCatalog/metrics/SegmentationMatrixSection.tsx
- modules/web/web-app/features/productCatalog/metrics/UnitConversionSection.tsx
- modules/web/web-app/lib/utils/params.ts
- modules/web/web-app/pages/tenants/catalog/productMetricDetail.tsx
- modules/web/web-app/pages/tenants/catalog/productMetrics.tsx
- modules/web/web-app/router/tenant/catalog.tsx
> feat: add metrics view and archive

- modules/meteroid/crates/meteroid-store/src/services/edge.rs
- modules/meteroid/crates/meteroid-store/src/services/invoice_lines/invoice_lines.rs
- modules/meteroid/crates/meteroid-store/src/services/invoices/draft.rs
- modules/meteroid/crates/meteroid-store/src/services/invoices/refresh.rs
> chore: Refresh only usage based invoice lines

- modules/meteroid/crates/meteroid-invoicing/src/svg.rs
- modules/meteroid/proto/api/invoices/v1/invoices.proto
- modules/meteroid/src/api/invoices/service.rs
- modules/meteroid/src/api_rest/files/router.rs
- modules/meteroid/src/services/invoice_rendering.rs
- modules/web/web-app/pages/tenants/invoice/Invoice.tsx
- modules/web/web-app/pages/tenants/invoice/invoiceCreate.tsx
> fix: invoice svg preview breaks on long invoice

- modules/meteroid/proto/api/quotes/v1/models.proto
- modules/meteroid/proto/portal/quotes/v1/models.proto
- modules/meteroid/proto/portal/quotes/v1/quotes.proto
it caused `pnpm --prefix modules/web/web-app run generate:proto` to fail
> chore: Cleanup quote proto files

- modules/meteroid/crates/meteroid-store/src/domain/tenants.rs
- modules/meteroid/crates/meteroid-store/src/repositories/tenants.rs
- modules/meteroid/src/api/organizations/service.rs
> chore: Disable email notifications by default on new organization (dev/sandbox)

- crates/common-domain/src/country.rs
> fix: soft fail on decode after country update

- modules/meteroid/src/services/currency_rates.rs
> fix: include base in historical rates
